// EX4
// FAZER UM LEVANTAMENTO DE DADOS! 

// ------- DICA NAO DESCARTAR DADOS -------
// DE 5 USUARIOS 
// NOME 
// SOBRENOME 
// CIDADE 
// IDADE 
// CPF
// SALDO DA CONTA BANCARIA 

// FAZER UMA MENSAGEM PARA CADA USUARIO! 

// DEPOIS FAZER A SOMA DE TODAS AS CONTAS BANCARIAS 
// E DIVIDIR POR 4 

//PRECISA TER!!
// LISTA
// IF E ELSE

// MILHONARIO 
// RICO 
// BEM DE VIDA 
// POBRE 
// INVALIDA 
lista_nome = ["lucas", "cris"]
usuario1 = (lista_nome[1])

